app/authentication/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField,SubmitField, BooleanField, ValidationError
from wtforms.validators import Required, Email, EqualTo
from ..models import User

class LoginForm(FlaskForm):
    username = StringField('Your Username', validators=[Required()])
    password = PasswordField('Password', validators = [Required()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

class RegistrationForm(FlaskForm):
    firstname = StringField('Enter your first name', validators = [Required()])
    lastname = StringField('Enter your last name', validators = [Required()])
    username = StringField('Enter your username', validators = [Required()])
    email = StringField('Your email address', validators=[Required(), Email()])
    password = PasswordField('Password', validators = [Required(), EqualTo('password_confirm', message = 'Passwords must match')])
    password_confirm = PasswordField('Confirm Password', validators = [Required()])
    submit = SubmitField('Sign Up')

    def validate_email(self, data_field):
        if User.query.filter_by(email = data_field.data).first():
            raise ValidationError('There is an account with that email!')

    def validate_username(self, data_field):
        if User.query.filter_by(username = data_field.data).first():
            raise ValidationError('That username is taken!')

app/authentication/__init__.py
from flask import Blueprint

authentication = Blueprint('authentication', __name__)

from . import views, forms

app/authentication/views.py
from flask import render_template, redirect, url_for, flash, request
from flask_login import login_user, logout_user, login_required
from ..models import User
from werkzeug.security import generate_password_hash, check_password_hash
from .forms import RegistrationForm, LoginForm
from ..email import mail_message
from .. import db
from . import authentication

@authentication.route('/', methods = ['GET', 'POST'])
def login():
    
    if request.form:
        uname = request.form['username']
        password = request.form['password']

        if uname != "" or password !="":
            user = User.query.filter_by(username = uname).first()
            # print(user.username)
            if user.verify_password(password):
                login_user(user)
                return redirect(request.args.get('next') or url_for('main.home'))
            else:
                flash('Invalid username or password')
        else:
            flash('Please fill in proper details')

    title = "Login"
    return render_template('authentication/login.html', title = title)


@authentication.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('authentication.login'))

@authentication.route('/register', methods = ['GET', 'POST'])
def register():
    if request.form:
        fname = request.form['firstName']
        print(fname)
        lname = request.form['lastName']
        uname = request.form['username']
        email = request.form['email']
        password = request.form['password']
        cpass = request.form['confirmPassword']

        if not email or not email.strip() or '@' not in email:
            flash('Please put in a valid email')
        elif fname != "" or lname != "" or uname != "" or password != "" or cpass != "":
            if uname == User.query.filter_by(username = uname).first():
                flash('Please pick a different username')
            elif password == cpass:
                password1 = generate_password_hash(password)
                user = User(firstname = fname, secondname = lname, username = uname, email = email, secured_password = password1)
                db.session.add(user)
                db.session.commit()
                mail_message("Karibu Thoughts", "email/karibu", user.email, user = user)
                return redirect(url_for('authentication.login'))
            else:
                flash('Your passwords do not match')
        else:
            flash("Fill all the fields")

    title = "New Account"
    return render_template('authentication/registration.html', title = title)







    

app/templates/authentication/login.html
{% import 'bootstrap/wtf.html' as wtf %}
{% extends 'base.html' %}


{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/login.css')}}">
{% endblock styles %} 

{% block title %}
    {% if title %}
        {{ title }}
    {% else %}
        Login
    {% endif %}
{% endblock title %}


{% block content %}

    <div class="container-fluid bigWrapper">
        <div class="loginForm">

            <div class="col-md-3 col1">
                {% for message in get_flashed_messages() %}
                <div class="alert alert-danger">
                    <button type="button" class="close" data-bs-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
            {% endfor %}
            </div>

            <div class="col col11">
                <form class="form-floating" action="" method = "POST">
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" name = "username" id="username" value = "{{ username }}" placeholder="Username" required>
                        <label for="username">Username</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control" name = "password" id="password" value = "{{ password }}" placeholder="Password" required> 
                        <label for="password">Password</label>
                    </div>
                    <button type="submit" action = "{{ url_for('authentication.login')}}" class="btn btn-outline-secondary">Sign In</button>
                </form>
                <div class="register">
                    <p> Don't have an account? <a href="{{url_for('authentication.register')}}">Sign up here</a></p>
                </div>
            </div>

            <div class="col-md-3 col1">

            </div>
        
        </div>
    </div>

{% endblock content %}

app/templates/authentication/registration.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as  wtf %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/register.css')}}">
{% endblock %} 

{% block title %}
    {% if title %}
        {{ title }}
    {% else %}
        Register with us 
    {% endif %}
{% endblock title %}

{% block content %}
    <div class="container-fluid bigWrapper">
        <div class="row">
            <div class="col-md-6 col1">
                 
            </div>
            <div class="col col2">

                <div class="registrationform">
                    <form class="form-floating" action = "" method = "POST">
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" name = "firstName" id="firstName" value = "{{ firstName }}" placeholder="First Name" required>
                            <label for="firstName">First Name</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" name = "lastName" id="lastName" value = "{{ lastName }}" placeholder="Last Name" required>
                            <label for="lastName">Last Name</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" name = "username" id="username" value = "{{ username }}" placeholder="Username" required>
                            <label for="username">Username</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="email" class="form-control" name = "email" id="email" value = "{{ email }}" placeholder="Email Address" required>
                            <label for="floatingInput">Email address</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="password" class="form-control" name = "password" id="password" value = "{{ password }}" placeholder="Password" required> 
                            <label for="password">Password</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="password" class="form-control" name = "confirmPassword" id="confirmPassword" value = "{{ confirmPassword }}" placeholder="Confirm Password" required>
                            <label for="confirmPassword">Confirm Password</label>
                        </div>
                        
                        <button type="submit" action = "{{ url_for('authentication.register')}}" class="btn btn-outline-secondary">Sign Up</button>
                    </form>
                </div>

            </div>
        </div>
    </div>
{% endblock content %}

<!-- {{ wtf.quick_form(registration_form) }} -->